#!/bin/bash

if [[ ! -z $1 ]]; then
	pathOpt="--path $1"
fi

if which swiftlint >/dev/null; then
    swiftlint lint --quiet $pathOpt
else
    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi